import { apiFetch, buyerHeaders, newIdempotencyKey } from './api'
import type {
  BuyerState,
  EventSummary,
  HoldResponse,
  OrderResponse,
  SeatMapResponse,
} from './seatTypes'

export function fetchEvents(): Promise<EventSummary[]> {
  return apiFetch<EventSummary[]>('/events')
}

export function fetchEvent(eventId: string): Promise<{ event: EventSummary }> {
  return apiFetch<{ event: EventSummary }>(`/events/${eventId}`)
}

export function fetchSeatMap(eventId: string): Promise<SeatMapResponse> {
  return apiFetch<SeatMapResponse>(`/events/${eventId}/seats`)
}

export function fetchBuyerState(eventId: string): Promise<BuyerState> {
  return apiFetch<BuyerState>(`/events/${eventId}/me`, { headers: buyerHeaders() })
}

/**
 * Takes a hold.
 *
 * <p>The idempotency key is generated by the caller and reused across retries of the *same*
 * intent. A fresh key per attempt would make a retry a second request, which is the bug the
 * header exists to prevent.
 */
export function createHold(
  eventId: string,
  request: { seatIds?: string[]; quantity?: number; together?: boolean },
  idempotencyKey: string,
): Promise<HoldResponse> {
  return apiFetch<HoldResponse>(`/events/${eventId}/holds`, {
    method: 'POST',
    headers: buyerHeaders(idempotencyKey),
    body: JSON.stringify(request),
  })
}

export function cancelHold(holdId: string): Promise<void> {
  return apiFetch<void>(`/holds/${holdId}`, { method: 'DELETE', headers: buyerHeaders() })
}

export function confirmOrder(
  holdId: string,
  idempotencyKey: string,
  paymentBehavior?: string,
): Promise<OrderResponse> {
  return apiFetch<OrderResponse>('/orders', {
    method: 'POST',
    headers: buyerHeaders(idempotencyKey),
    body: JSON.stringify(paymentBehavior ? { holdId, paymentBehavior } : { holdId }),
  })
}

export function fetchOrder(orderId: string): Promise<OrderResponse> {
  return apiFetch<OrderResponse>(`/orders/${orderId}`, { headers: buyerHeaders() })
}

export { newIdempotencyKey }
